import type { Metadata } from "next";
import { Noto_Sans_KR, Noto_Serif_KR } from "next/font/google";
import React, { Suspense } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "@/styles/globals.css";
import TopLoadingBar from "@/components/layout/TopLoadingBar";
import { BookProvider } from "@/context/bookContext";
import LayoutWrapper from "@/components/layout/layoutWrapper";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto-sans-kr",
});

const notoSerifKR = Noto_Serif_KR({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto-serif-kr",
});

export const metadata: Metadata = {
  title: "DMZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${notoSansKR.variable} ${notoSerifKR.variable}`}
    >
      <body
        className="min-h-screen flex items-center justify-center overflow-hidden relative bg-gradient-to-br from-[#0a0a1a] via-[#1a1a3e] to-[#2a2a5e]"
        style={{ fontFamily: "'Diphylleia', serif" }}
      >
        <BookProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </BookProvider>

        <ToastContainer
          position="top-right"
          autoClose={3000}
          theme="light"
        />

        <Suspense fallback={null}>
          <TopLoadingBar />
        </Suspense>
      </body>
    </html>
  );
}